## **Create a pandas dataframe (DataFrame name as 'df') with numpy random values (4 features and 4 observation)**

In [11]:
import pandas as pd
import numpy as np
import random
random.seed(42)
ages = [np.random.randint(18, 45) for _ in range(4)]
Salaries = [np.random.randint(50000, 800000) for _ in range(4)]
cities= ['Mumbai', 'Delhi', 'Kolkata', 'Hyderabad', 'Bangalore', 'Chennai']
City = [np.random.choice(cities) for _ in range(4)]
Degree=['Bachelor', 'Master', 'BBA', 'Doctor']
Education=[np.random.choice(Degree) for _ in range(4)]
data = {
    'Age': ages,
    'Salary': Salaries,
    'Education Level': Education,
    'Living City': City,

}
df = pd.DataFrame(data)
df

   Age  Salary Education Level Living City
0   35  682527        Bachelor       Delhi
1   21  749934          Doctor     Kolkata
2   40  781540             BBA       Delhi
3   18  200704        Bachelor      Mumbai

# **Rename the task - 1 'df' dataframe column names to 'Random value 1', 'Random value 2', 'Random value 3' & 'Random value 4**

In [12]:
df.rename(columns={'Age':'Random value 1','Salary':'Random value 2','Education Level':'Random value 3','Living City':'Random value 4'},inplace=True)
df

   Random value 1  Random value 2 Random value 3 Random value 4
0              35          682527       Bachelor          Delhi
1              21          749934         Doctor        Kolkata
2              40          781540            BBA          Delhi
3              18          200704       Bachelor         Mumbai

# **Find the descriptive statistics of the 'df' dataframe.**

In [13]:
df.describe()

       Random value 1  Random value 2
count        4.000000        4.000000
mean        28.500000   603676.250000
std         10.661457   271803.187401
min         18.000000   200704.000000
25%         20.250000   562071.250000
50%         28.000000   716230.500000
75%         36.250000   757835.500000
max         40.000000   781540.000000

# **Check for the null values in 'df' and find the data type of the columns.**

In [14]:
df.isnull().any()

Random value 1    False
Random value 2    False
Random value 3    False
Random value 4    False
dtype: bool

In [15]:
data=df.dtypes
data

Random value 1     int64
Random value 2     int64
Random value 3    object
Random value 4    object
dtype: object

# **Display the 'Random value 2' & 'Random value 3' columns with location method and index location method.**

In [16]:
df.loc[:,['Random value 2','Random value 3']]

   Random value 2 Random value 3
0          682527       Bachelor
1          749934         Doctor
2          781540            BBA
3          200704       Bachelor

In [17]:
df.iloc[:,[1,2]]

   Random value 2 Random value 3
0          682527       Bachelor
1          749934         Doctor
2          781540            BBA
3          200704       Bachelor